---
title: "propeller_plot"
author: "Leonardo Feitosa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(data.table)

# data directory from gdrive
basedir <- "G:/Meu Drive/PRM review/"
datadir <- file.path(basedir, "data/fish_base_data")
outdir <- file.path(basedir, "data/outputs") 

```


```{r}
# read in the  data
iucn_data <- read_csv(here("data", "iucn_data", "assessments.csv")) %>% 
  clean_names() %>% 
  filter(str_detect(systems, "Marine") & str_detect(threats, "longline") | str_detect(scientific_name,"Squatina|Isogomphodon|Carcharhinus|Eusphyra|Orectolobus|Pristiophorus|Mustelus")) %>% # list of genera to keep in the filtering
  select(scientific_name, redlist_category, year_published) %>% 
  mutate(redlist_category = case_when(
    str_detect(redlist_category, "Near") ~ "NT",
    str_detect(redlist_category, "Vul") ~ "VU",
    str_detect(redlist_category, "Data") ~ "DD",
    redlist_category == "Endangered" ~ "EN",
    redlist_category == "Critically Endangered" ~ "CR",
    str_detect(redlist_category, "Least") ~ "LC",
    TRUE ~ redlist_category
  ))

iucn_data_non_longline <- read_csv(here("data", "iucn_data", "assessments.csv")) %>% 
  clean_names() %>% 
  filter(str_detect(systems, "Marine") & !str_detect(threats, "longline")) 

sim_results <- read_csv(here::here(basedir, "data", "simulation_results.csv")) %>% 
  filter(scenario != "CQ") %>% 
  filter(!is.na(mort_scenario)) %>% 
  filter(mort_scenario == "BAU" | mort_scenario == "Median Mortality") %>% 
  mutate(f_mort = ((100 * f) - (100 * f * (1-mid_avm) * (1-mid_prm)))/100) %>%  
  select(scientific_name, f, f_mort) %>% 
  distinct()

sim_results <- read_csv(here::here( "data", "simulation_results.csv")) %>% 
  filter(scenario != "CQ") %>% 
  filter(!is.na(mort_scenario)) %>% 
  filter(mort_scenario == "BAU" | mort_scenario == "Median Mortality") %>% 
  mutate(f_mort = ((100 * f) - (100 * f * (1-mid_avm) * (1-mid_prm)))/100) %>%  
  select(scientific_name, f, f_mort) %>% 
  distinct()

top_shark_mort <- read_csv(here("data", "saup_eez_high_seas_shark_mortality.csv")) %>% 
  group_by(scientific_name) %>% 
  summarise(mort_sum = sum(mortality)) %>% 
  arrange(desc(mort_sum))

new_dat <- read_csv(here::here("data", "iucn_fishbase_list.csv")) %>% 
  select(-11, -12, -13, -14, -15) %>% 
  select(scientific_name, common_name)

sim_results = left_join(sim_results, new_dat)

# write_csv(sim_results, here::here("data", "f_sim_results.csv"))
```

```{r}
sim_results = read_csv(here::here("data", "f_sim_results.csv"))

# data wrangling for the plot
sim_results_iucn <- sim_results %>% 
  left_join(iucn_data, by = "scientific_name")

sim_results_top = left_join(top_shark_mort, sim_results_iucn) %>% 
  filter(!is.na(f))

sim_results_iucn_pct <- sim_results_iucn %>% 
  mutate(percent_diff = (f - f_mort) / f * 100) %>% 
  mutate(percent_diff = round(percent_diff, 4)) %>% 
#  filter(redlist_category %in% c("VU", "EN", "CR")) %>% 
  rowid_to_column("id") %>% 
  mutate(id = fct_reorder(as.factor(id), percent_diff)) %>% 
  mutate(redlist_category = as.factor(redlist_category)) %>% 
  arrange(id) %>% 
  select(-scientific_name) %>% 
  rename(scientific_name = common_name)

sim_results_iucn_pct_threat <- sim_results_iucn_pct %>% 
  filter(redlist_category != "DD")

threatended = sim_results_iucn_pct %>% 
  filter(redlist_category %in% c("VU", "EN", "CR")) %>% 
  mutate(mean_percent_diff = mean(percent_diff, na.rm = TRUE))

non_threat = sim_results_iucn %>% 
  mutate(percent_diff = (f - f_mort) / f * 100) %>% 
  mutate(percent_diff = round(percent_diff, 4)) %>% 
  filter(redlist_category %in% c("DD", "NT", "LC")) %>% 
  rowid_to_column("id") %>% 
  mutate(id = fct_reorder(as.factor(id), percent_diff)) %>% 
  mutate(redlist_category = as.factor(redlist_category)) %>% 
  arrange(id)   %>% 
  select(-scientific_name) %>% 
  rename(scientific_name = common_name) 

non_threat_mean <- non_threat %>% 
  mutate(mean_percent_diff = mean(percent_diff, na.rm = TRUE))
  
# Set a number of empty bars to add at the end of each group
empty_bar <- 7
to_add <- data.frame(matrix(NA, empty_bar*nlevels(sim_results_iucn_pct_threat$redlist_category), ncol(sim_results_iucn_pct_threat)))
colnames(to_add) <- colnames(sim_results_iucn_pct_threat)
to_add$redlist_category <- rep(levels(sim_results_iucn_pct_threat$redlist_category), each = empty_bar)
sim_results_iucn_pct_threat <- rbind(sim_results_iucn_pct_threat, to_add)
sim_results_iucn_pct_threat <- sim_results_iucn_pct_threat %>% arrange(redlist_category)
sim_results_iucn_pct_threat$id <- seq(1, nrow(sim_results_iucn_pct_threat))

# get the name and the y position of each label
label_data_m <- sim_results_iucn_pct_threat 
number_of_bar <- nrow(label_data_m)
angle <- 90 - 360 * (label_data_m$id - 0.5) /  number_of_bar
label_data_m$hjust <- ifelse(angle < -90, 1, 0)
label_data_m$angle <- ifelse(angle < -90, angle + 180, angle)

# Not sure how to use the code below 
redlist_breaks <- sim_results_iucn_pct_threat %>% 
    group_by(redlist_category) %>% 
    summarize(start = min(id), 
              end = max(id) - 3) %>% 
    rowwise() %>% 
    mutate(title = mean(c(start, end))) %>% 
    ungroup() %>% 
    mutate(end = data.table::shift(end + 1, n = 1, type = "shift", fill = max(end) + 1),
           start = start -1)

max_value <- max(sim_results_iucn_pct_threat$percent_diff, na.rm = T)
  
y_max <- 20 * ceiling(max_value/20)

v <- c(20, 40, 60, 80, 100)

redlist_breaks <- redlist_breaks %>% 
  mutate(v = list(v)) %>% 
  unnest(cols = c(v))
```

```{r}
# get improvement averages per iucn status
sim_results_iucn_pct_plot_m_ave <- sim_results_iucn_pct %>%
  summarise(mean_percent_diff = mean(percent_diff, na.rm = TRUE),
            sd_percent_diff = sd(percent_diff, na.rm = TRUE))

sim_results_iucn_pct_plot_m_ave2 <- sim_results_iucn_pct_threat %>% 
  filter(redlist_category != "DD") %>% 
  summarise(mean_percent_diff = mean(percent_diff, na.rm = TRUE)) %>% 
  slice_head(n = 1)
```



```{r, fig.height = 10, fig.width=10}
prop = ggplot(data = sim_results_iucn_pct_threat) +
    geom_segment(data = redlist_breaks %>% 
                   filter(v != 100),
               aes(x = end, y = v, xend = start, yend = v),
               color = "grey", linewidth = 0.3, inherit.aes = FALSE) +
  annotate("text",
             x = rep(max(sim_results_iucn_pct_threat$id, length(v))),
             y = v -5, label = paste0(head(v), "%"), color = "grey", size = 5, angle = 0, fontface = "bold", hjust = 0.7) +
    geom_col(aes(x = id, 
               y = percent_diff, 
               fill = redlist_category),
             show.legend = F,
           width = 0.8) +
  ylim(-40, max(sim_results_iucn_pct_threat$percent_diff)) +
  scale_fill_manual(values = c("#E31A1C","#FD8D3C", "#FED976")) +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.margin = unit(rep(0, 4), "cm")) +
  coord_polar(start = 0) +
 geom_text(data = label_data_m, 
            aes(x = id, y = percent_diff + 15, label = scientific_name, angle = angle),
           nudge_x = -0.25, nudge_y = 0.25,
              color = "black", size = 4, inherit.aes = FALSE) +
  geom_segment(data = redlist_breaks,
               aes(x = start, y = -5, xend = end, yend = -5),
               colour = "black", alpha = 0.8, inherit.aes = FALSE) +
  geom_text(data = redlist_breaks,
            aes(x = title, y = -18, label = redlist_category, color = redlist_category),
            show.legend = F,
            hjust = 1, alpha = 0.8, size = 5, fontface = "bold", inherit.aes = FALSE) +
  scale_color_manual(values = c("#E31A1C", "#FD8D3C", "#FED976")) +
  # geom_text(data = redlist_breaks, 
  #             aes(x = title, y = 48, label = redlist_category),  colour = "black", alpha = 0.8, size = 5, fontface = "bold", inherit.aes = FALSE) +
  labs(fill = "Redlist Category") + #y = 80
  theme_minimal(base_size = 14) +
  labs(x = "",
       y = "")
prop

ggsave(prop, file = paste0("fig4.pdf"), path = here::here("figs"), height = 20, width = 20)
```



```{r}
non_threat = sim_results_iucn %>% 
  mutate(percent_diff = (f - f_mort) / f * 100) %>% 
  mutate(percent_diff = round(percent_diff, 4)) %>% 
  filter(redlist_category %in% c("DD", "NT", "LC")) %>% 
  rowid_to_column("id") %>% 
  mutate(id = fct_reorder(as.factor(id), percent_diff)) %>% 
  mutate(redlist_category = as.factor(redlist_category)) %>% 
  arrange(id)   %>% 
  select(-scientific_name) %>% 
  rename(scientific_name = common_name)

non_threat_mean <- non_threat %>% 
  mutate(mean_percent_diff = mean(percent_diff, na.rm = TRUE))
  

# Set a number of empty bars to add at the end of each group
empty_bar <- 7
to_add <- data.frame(matrix(NA, empty_bar*nlevels(non_threat$redlist_category), ncol(non_threat)))
colnames(to_add) <- colnames(non_threat)
to_add$redlist_category <- rep(levels(non_threat$redlist_category), each = empty_bar)
non_threat <- rbind(non_threat, to_add)
non_threat <- non_threat %>% arrange(redlist_category)
non_threat$id <- seq(1, nrow(non_threat))

# get the name and the y position of each label
label_data_m <- non_threat 
number_of_bar <- nrow(label_data_m)
angle <- 90 - 360 * (label_data_m$id - 0.5) /  number_of_bar
label_data_m$hjust <- ifelse(angle < -90, 1, 0)
label_data_m$angle <- ifelse(angle < -90, angle + 180, angle)

# Not sure how to use the code below 
redlist_breaks <- non_threat %>% 
    group_by(redlist_category) %>% 
    summarize(start = min(id), 
              end = max(id) - 3) %>% 
    rowwise() %>% 
    mutate(title = mean(c(start, end))) %>% 
    ungroup() %>% 
    mutate(end = data.table::shift(end + 1, n = 1, type = "shift", fill = max(end) + 1),
           start = start -1)

max_value <- max(non_threat$percent_diff, na.rm = T)
  
y_max <- 20 * ceiling(max_value/20)

v <- c(20, 40, 60, 80, 100)

redlist_breaks <- redlist_breaks %>% 
  mutate(v = list(v)) %>% 
  unnest(cols = c(v))
```

```{r, fig.height = 10, fig.width=10}
prop = ggplot(data = non_threat) +
    geom_segment(data = redlist_breaks %>% 
                   filter(v != 100),
               aes(x = end, y = v, xend = start, yend = v),
               color = "grey", linewidth = 0.3, inherit.aes = FALSE) +
  annotate("text",
             x = rep(max(non_threat$id, length(v))),
             y = v -5, label = paste0(head(v), "%"), color = "grey", size = 5, angle = 0, fontface = "bold", hjust = 0.7) +
    geom_col(aes(x = id, 
               y = percent_diff, 
               fill = redlist_category),
             show.legend = F,
           width = 0.8) +
  ylim(-40, max(non_threat$percent_diff)) +
  scale_fill_manual(values = c("grey", "#91CF60", "#1A9850")) +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        plot.margin = unit(rep(0, 4), "cm")) +
  coord_polar(start = 0) +
 geom_text(data = label_data_m, 
            aes(x = id, y = percent_diff + 15, label = scientific_name, angle = angle),
           nudge_x = -0.25, nudge_y = 0.25,
              color = "black", size = 4, inherit.aes = FALSE) +
  geom_segment(data = redlist_breaks,
               aes(x = start, y = -5, xend = end, yend = -5),
               colour = "black", alpha = 0.8, inherit.aes = FALSE) +
  geom_text(data = redlist_breaks,
            aes(x = title, y = -18, label = redlist_category, color = redlist_category),
            show.legend = F,
            hjust = 1, alpha = 0.8, size = 5, fontface = "bold", inherit.aes = FALSE) +
  scale_color_manual(values = c( "grey", "#91CF60", "#1A9850")) +
  # geom_text(data = redlist_breaks, 
  #             aes(x = title, y = 48, label = redlist_category),  colour = "black", alpha = 0.8, size = 5, fontface = "bold", inherit.aes = FALSE) +
  labs(fill = "Redlist Category") + #y = 80
  theme_minimal(base_size = 14) +
  labs(x = "",
       y = "")
prop

ggsave(prop, file = paste0("propeller_plot_non_threat.pdf"), path = here::here("figs", "supp"), height = 20, width = 20)
```
