---
title: "data_summary"
author: "Leonardo Feitosa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE)
library(tidyverse)
library(here)
library(ggh4x)
library(patchwork)

# Set data paths
basedir <- "G:/Meu Drive/PRM review/"
datadir <- file.path(basedir, "data/fish_base_data")
outdir <- file.path(basedir, "data/outputs") # calls present data from raster files
```

```{r}
# read in the data
prm_elasmo <- read_csv(here("data", "prm_dataset_updated.csv")) 
```

```{r}
# calculating mean values for those taxa at higher levels than species
## Dasyatis sp
dasyatis_sp <- prm_elasmo %>% 
  filter(str_detect(family, "Dasyatidae")) %>% 
  mutate(mean_size = mean(max_size_cm, na.rm = TRUE),
         mean_depth = mean(median_depth, na.rm = TRUE))

## Squalus sp
squalus_sp <- prm_elasmo %>% 
  filter(str_detect(scientific_name, "Squalus")) %>% 
  mutate(mean_size = mean(max_size_cm, na.rm = TRUE),
         mean_depth = mean(median_depth, na.rm = TRUE))

## Mustelus sp
mustelus_sp <- prm_elasmo %>% 
  filter(str_detect(scientific_name, "Mustelus")) %>% 
  mutate(mean_size = mean(max_size_cm, na.rm = TRUE),
         mean_depth = mean(median_depth, na.rm = TRUE))

## Centrophorus sp
centrophorus_sp <- prm_elasmo %>% 
  filter(str_detect(scientific_name, "Centrophorus")) %>% 
  mutate(mean_size = mean(max_size_cm, na.rm = TRUE),
         mean_depth = mean(median_depth, na.rm = TRUE))

## sharks
sharks <- prm_elasmo %>% 
  filter(str_detect(common_name, "shark")) %>% 
  mutate(mean_size = mean(max_size_cm, na.rm = TRUE),
         mean_depth = mean(median_depth, na.rm = TRUE))

## rays
rays <- prm_elasmo %>% 
  filter(str_detect(measure, "disk_width")) %>% 
  mutate(mean_size = mean(max_size_cm, na.rm = TRUE),
         mean_depth = mean(median_depth, na.rm = TRUE))

prm_elasmo_count <- prm_elasmo %>% 
  select(estimate_type, reference) %>% 
  group_by(estimate_type) %>% 
  count()
```


```{r}
# data wrangling
prm_elasmo_subset <- prm_elasmo %>% 
  select(scientific_name, gear_class, habitat_associated, estimate_type, estimate, sample_size,
         method, ventilation_method, max_size_cm, measure, median_depth, reproductive_mode, family) %>% 
  mutate(max_size_cm = case_when( # filling missing information based on the average per group
    scientific_name == "Dasyatis sp" ~ 143.36,
    scientific_name == "Squalus sp" ~ 166.36,
    scientific_name == "Mustelus sp" ~ 167.24,
    scientific_name == "Centrophorus sp" ~ 165.75,  
    scientific_name == "sharks" ~ 351.6828,
    scientific_name == "rays" ~ 164.261, # only calculated for the batoid species with disk width measures
    TRUE ~ max_size_cm
  )) %>% 
  mutate(median_depth = case_when( # filling missing information based on the average per group
    scientific_name == "Dasyatis sp" ~ 117.63,
    scientific_name == "Squalus sp" ~ 767.786,
    scientific_name == "Mustelus sp" ~ 246.1,
    scientific_name == "Centrophorus sp" ~ 1136.25,
    scientific_name == "sharks" ~ 309.9474,
    scientific_name == "rays" ~ 99.87,
    TRUE ~ median_depth
  )) %>% 
  mutate(measure = case_when(
    scientific_name == "sharks" ~ "total_length",
    scientific_name %in% c("rays", "Dasyatis sp") ~ "disk_width",
    TRUE ~ measure
  )) %>% 
  mutate(reproductive_mode = case_when(
    scientific_name == "sharks" ~ "yolk-sac viviparity",
    scientific_name == "rays" ~ "yolk-sac viviparity",
    TRUE ~ reproductive_mode
  )) %>%
  mutate_if(is.character, as.factor) %>% 
  mutate(group = case_when(
    str_detect(family, "Mobulidae|Dasyatidae|Gymnyridae|Myliobatidae|Torpedinidae|Rhinobatidae|Rhinidae|Aetobatidae|Rajidae|Pristidae") ~ "Batoids",
    str_detect(scientific_name, "Himantura|Dasyatis|Gymnura|Neotrygon|Bathytoshia|rays|Rhinoptera|Rhynchobatus|Aptychotrema|Trygon") ~ "Batoids",
    TRUE ~ "Sharks"
  )) %>% 
  mutate(estimate = case_when(
    estimate_type == "post-release survival" ~ 1 - estimate, # Converts post-release survival into PRM
    TRUE ~ estimate
  )) %>% 
  mutate(estimate_type = case_when(
    estimate_type == "post-release survival" ~ "post-release mortality",
    TRUE ~ estimate_type
  ))

#write_csv(prm_elasmo_subset, file = here("data", "prm_elasmo_subset.csv"), col_names = TRUE, na = "")

prm_sharks <- prm_elasmo_subset %>% 
  filter(group == "Sharks") %>% 
  distinct(scientific_name)

prm_batoids <- prm_elasmo_subset %>% 
  filter(group == "Batoids") %>% 
  distinct(scientific_name)

# Create subset of the whole dataset with at-vessel mortality and calculate the weighted averages per species
mort_summary <- prm_elasmo_subset %>% 
  filter(estimate > 0) %>% 
  mutate(est_count = sample_size * estimate) %>% 
  group_by(scientific_name, estimate_type) %>% 
  mutate(mortality_prop = sum(est_count) / sum(sample_size)) %>% 
  ungroup() %>% 
  mutate(prm = ifelse(estimate_type == "post-release mortality", mortality_prop, NA),
         avm = ifelse(estimate_type == "at-vessel mortality", mortality_prop, NA)) 

# create mortality subset 
mort_subset <- mort_summary %>% 
  arrange(avm) %>% 
  select(scientific_name, avm) %>% 
  distinct(scientific_name) %>% 
  pull(scientific_name)  

elasmo_avm <- prm_elasmo_subset %>%
  filter(estimate_type == "at-vessel mortality" & estimate > 0) %>% 
  mutate(est_count = sample_size * estimate) %>% 
  group_by(scientific_name) %>% 
  mutate(mortality_prop = sum(est_count) / sum(sample_size)) %>% 
  drop_na() %>% 
  filter(!gear_class %in% c("handline", "purse seine"))

# Create subset of the whole dataset with post-release mortality and calculate the weighted averages per species
elasmo_prm <- prm_elasmo_subset %>% 
  filter(estimate_type == "post-release mortality" & estimate > 0) %>% 
  mutate(est_count = sample_size * estimate) %>% 
  group_by(scientific_name) %>% 
  mutate(mortality_prop = sum(est_count) / sum(sample_size)) %>% 
  drop_na() %>% 
  filter(!gear_class %in% c("handline", "purse seine", "pole and line"))

# get weighted average mortality for each mortality type
#sharks
mort_summary_subset <- mort_summary %>% 
  filter(group == "Sharks" & gear_class %in% c("longline", "gillnet", "trawl")) %>% 
  group_by(estimate_type, gear_class) %>% 
  summarise(mean = mean(mortality_prop))

# batoids
mort_summary_subset_bat <- mort_summary %>% 
  filter(group == "Batoids" & gear_class %in% c("longline", "gillnet", "trawl")) %>% 
  group_by(estimate_type, gear_class) %>% 
  summarise(mean = mean(mortality_prop))
```

```{r}
# get summary stats for AVM per family
mort_summary_fam <- mort_summary %>% 
  filter(estimate_type == "at-vessel mortality" & gear_class %in% c("longline", "gillnet", "trawl")) %>% 
  group_by(family, gear_class) %>% 
  summarise(mean_avm = mean(mortality_prop))
```

```{r}
# get summary stats for which locations studies were conducted
elasmo_prm_location <- prm_elasmo %>%
  mutate(location_clean = case_when(
    str_detect(location, "Texas") ~ "USA",
    str_detect(location, "California") ~ "USA",
    str_detect(location, "Alabama") ~ "USA",
    str_detect(location, "Rhode Island") ~ "USA",
    str_detect(location, "Massachussets") ~ "USA",
    str_detect(location, "New York") ~ "USA",
    str_detect(location, "Carolina") ~ "USA",
    str_detect(location, "Virginia") ~ "USA",
    str_detect(location, "Hawaii") ~ "USA",
    str_detect(location, "Maine") ~ "USA",
    str_detect(location, "Biscay") ~ "France",
    str_detect(location, "Galicia") ~ "Spain",
    str_detect(location, "Grand banks") ~ "Canada",
    str_detect(location, "Australia") ~ "Australia",
    str_detect(location, "Mexico") ~ "Mexico",
    str_detect(location, "Leone") ~ "Sierra Leone",
    str_detect(location, "South Wales") ~ "Australia",
    str_detect(location, "Tasmania") ~ "Australia",
    str_detect(location, "Antalya") ~ "Turkey",
    str_detect(location, "English") ~ "England",
    str_detect(location, "USA") ~ "USA",
    TRUE ~ location
  )) %>% 
  select(reference, location_clean, estimate_type) %>% 
  distinct() %>% 
  group_by(estimate_type, location_clean) %>% 
  summarise(count = n()) %>%
    drop_na() %>% 
  ungroup() %>% 
  mutate(sum = sum(count)) 


elasmo_prm_location_subset <- elasmo_prm_location %>% 
  filter(location_clean %in% c("USA", "Florida", "Australia", "Spain", "France", "Canada", "England", "New Zealand")) %>% 
  mutate(location_clean = case_when(
    location_clean == "Florida" ~ "USA",
    TRUE ~ location_clean
  )) %>% 
  select(-estimate_type) %>%
  group_by(location_clean) %>% 
  mutate(sum = sum(count)) %>% 
  ungroup() %>% 
  mutate(total = sum(count)) %>% 
  mutate(percentages = 100 * sum/ total) %>% 
  distinct() %>% 
  arrange(desc(percentages))
```


```{r}
# get summary stats
## number of studies per major gear
prm_elasmo_subset_gear <- prm_elasmo %>%
  filter(gear_class %in% c("longline", "gillnet", "trawl")) %>% 
  select(gear_class, reference) %>% 
  distinct() %>% 
  group_by(gear_class) %>% 
  mutate(count = n()) %>% 
  select(gear_class, count) %>% 
  distinct()

# number of species per type of mortality
prm_elasmo_subset_sp <- prm_elasmo_subset %>% 
  distinct(group, estimate_type, scientific_name) %>% 
  group_by(group, estimate_type) %>% 
  summarise(count = n())
```



```{r, fig.height=12, fig.width=8}
mort_proportions_plot_sp <-
  ggplot(data = mort_summary %>% 
           filter(!gear_class %in% c("handline", "purse seine", "pole and line")) %>% 
              mutate(estimate_type = str_to_sentence(estimate_type),
                     gear_class = str_to_title(gear_class))) +
  geom_line(aes(x = fct_rev(factor(scientific_name, levels = mort_subset)), 
                 y = mortality_prop,
                 group = scientific_name),
            show.legend = F,
             color = "gray30",
             linewidth = 0.6,
             alpha = 0.5) +
  geom_point(aes(x = fct_rev(factor(scientific_name, levels = mort_subset)), 
                 y = mortality_prop,
                 color = estimate_type),
             size = 1.5,
             alpha = 0.9,
             show.legend = F) +
  facet_grid(factor(group, levels = c("Sharks", "Batoids")) ~ factor(gear_class,
                    levels = c("Longline", "Gillnet", "Trawl")),
             scales = "free_y",
             space = "free_y") +
  labs(x = "",
       y = "Fishing mortality",
       color = "Estimate type") +
  scale_y_continuous(expand = c(0.01, 0.01)) +
  scale_color_manual(values = c("#414487FF", "#22A884FF")) +
  scale_shape(guide = 'none') +
  coord_flip() +
  theme_bw(base_size = 14) +
  theme(axis.text = element_text( color = "black"),
        axis.text.y = element_text(face = "italic"),
        axis.title = element_text( color = "black"),
        legend.position = "bottom",
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        strip.background = element_rect(fill = "transparent"),
        panel.spacing.x = unit(5, "mm"))

#ggsave(mort_proportions_plot_sp, file = paste0("mort_proportions_plot_sp.png"), path = here::here("figs"), height = 12, width = 8)
```



```{r}
# Create subset of the whole dataset with at-vessel mortality and calculate the weighted averages per family 
mort_summary_fam <- prm_elasmo_subset %>%
  filter(estimate > 0) %>% 
  mutate(est_count = sample_size * estimate) %>% 
  group_by(family, estimate_type) %>% 
  mutate(mortality_prop = sum(est_count) / sum(sample_size)) %>% 
  ungroup() %>% 
  drop_na() %>% 
  mutate(prm = ifelse(estimate_type == "post-release mortality", mortality_prop, NA),
         avm = ifelse(estimate_type == "at-vessel mortality", mortality_prop, NA))  

mort_subset_fam <- mort_summary_fam %>% 
  arrange(avm) %>% 
  select(family, avm) %>% 
  distinct(family) %>% 
  pull(family) 

mort_summary_fam_seg <- mort_summary_fam %>% 
  pivot_wider(names_from = estimate_type,
              values_from = mortality_prop)

# Create subset of the whole dataset with at-vessel mortality and calculate the weighted averages per species 
elasmo_avm_fam <- elasmo_avm %>%
  group_by(family) %>% 
  summarise(mean_prop = mean(mortality_prop))
  
# Create subset of the whole dataset with post-release mortality and calculate the weighted averages per species 
elasmo_prm_fam <- elasmo_prm %>% 
  group_by(family) %>% 
  summarise(mean_prop = mean(mortality_prop))

# family boxplot subset 
boxplot_subset <- 
  mort_summary %>%  
  group_by(family, estimate_type, gear_class) %>% 
  mutate(n = n()) %>% 
  filter(n > 2) %>% 
  ungroup()

# habitat associated boxplot subset
habitat_subset <-
  mort_summary %>% 
  group_by(habitat_associated, estimate_type, gear_class) %>%
  mutate(n = n()) %>%  
  filter(n > 2)
```



```{r, fig.height=8, fig.width=8, message = TRUE}
mort_proportions_plot_fam <-
  ggplot() +
  geom_point(data = mort_summary %>% 
           filter(!gear_class %in% c("handline", "purse seine", "pole and line") &
                  group == "Sharks") %>% 
              mutate(estimate_type = str_to_sentence(estimate_type),
                     gear_class = str_to_title(gear_class)) %>% 
           drop_na(family) %>% 
             mutate(family = as.factor(family)) %>% 
             arrange(desc(family)),
           aes(x = fct_inorder(family),
                y = mortality_prop,
                color = estimate_type, group = estimate_type),
            position = position_jitterdodge(jitter.width = .1),
         show.legend = F) +
  geom_boxplot(data = boxplot_subset %>% 
                 filter(!gear_class %in% c("handline", "purse seine", "pole and line")  &
                  group == "Sharks") %>% 
              mutate(estimate_type = str_to_sentence(estimate_type),
                     gear_class = str_to_title(gear_class)) %>% 
           drop_na(family) %>% 
             mutate(family = as.factor(family)) %>% 
             arrange(desc(family)),
               aes(x = fct_inorder(family), 
                 y = mortality_prop, 
                 fill = estimate_type),
             show.legend = F,
             alpha = 0.5,
         fatten = 1) +
  geom_hline(data = mort_summary_subset %>% 
               mutate(estimate_type = str_to_sentence(estimate_type),
                     gear_class = str_to_title(gear_class)),
             aes(yintercept = mean, color = estimate_type),
             show.legend = F,
             linetype = "dashed",
             alpha = 0.7,
             linewidth = .9) +
  facet_wrap(~ factor(gear_class,
                    levels = c("Longline", "Gillnet", "Trawl"))) +
  labs(x = "",
       y = "Fishing mortality",
       color = "Estimate type",
       fill = "Estimate type") +
  scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1)) +
  scale_color_manual(values = c("#414487FF", "#22A884FF")) +
  scale_fill_manual(values = c("#414487FF", "#22A884FF")) +
  coord_flip() +
  theme_bw(base_size = 14) +
  theme(axis.text = element_text( color = "black"),
        axis.title = element_text(color = "black"),
        legend.position = "bottom",
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        strip.background = element_rect(fill = "transparent"),
        panel.spacing.x = unit(5, "mm"))

#ggsave(mort_proportions_plot_fam, file = paste0("mort_proportions_plot_fam.png"), path = here::here("figs"), height = 12, width = 8)
```

```{r, fig.height=8, fig.width=6}
habitat_plot <- 
  ggplot() +
  geom_point(data = mort_summary %>% 
         filter(!gear_class %in% c("handline", "purse seine", "pole and line") &
                  !is.na(habitat_associated) &
                  group == "Sharks") %>% 
         mutate(estimate_type = str_to_sentence(estimate_type),
                gear_class = str_to_title(gear_class)) %>% 
         mutate(habitat_associated = str_to_title(habitat_associated),
                gear_class = str_to_title(gear_class)) %>% 
         mutate(habitat_associated = as.factor(habitat_associated)) %>% 
         arrange(desc(habitat_associated)),
         aes(x = fct_inorder(habitat_associated),
             y = mortality_prop, 
             color = estimate_type, group = estimate_type),
             position = position_jitterdodge(jitter.width = .1)) +
  geom_boxplot(data = habitat_subset %>% 
         filter(!gear_class %in% c("handline", "purse seine", "pole and line") &
                  !is.na(habitat_associated) &
                  group == "Sharks") %>% 
         mutate(estimate_type = str_to_sentence(estimate_type),
                gear_class = str_to_title(gear_class)) %>% 
         mutate(habitat_associated = str_to_title(habitat_associated),
                gear_class = str_to_title(gear_class)) %>% 
         mutate(habitat_associated = as.factor(habitat_associated)) %>% 
         arrange(desc(habitat_associated)),
         aes(x = fct_inorder(habitat_associated), 
             y = mortality_prop, 
             fill = estimate_type),
               alpha = 0.5,
         fatten = 1) +
  geom_hline(data = mort_summary_subset %>% 
               mutate(estimate_type = str_to_sentence(estimate_type),
                     gear_class = str_to_title(gear_class)),
             aes(yintercept = mean, color = estimate_type),
             show.legend = F,
             linetype = "dashed",
             alpha = 0.7,
             linewidth = .9) +
  facet_wrap(~ factor(gear_class,
                    levels = c("Longline", "Gillnet", "Trawl"))) +
  labs(x = "",
       y = "Fishing mortality",
       color = "Estimate type",
       fill = "Estimate type") +
  scale_color_manual(values = c("#414487FF", "#22A884FF")) +
  scale_fill_manual(values = c("#414487FF", "#22A884FF")) +
  coord_flip() +
  theme_bw(base_size = 42) +
  theme(axis.text = element_text( color = "black"),
        axis.title = element_text(color = "black"),
        legend.position = "bottom",
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        strip.background = element_rect(fill = "transparent"),
        panel.spacing.x = unit(5, "mm")) 

#ggsave(habitat_plot, file = paste0("habitat_plot.pdf"), path = here::here("figs", "poster"), height = 15, width = 30)
```

```{r, fig.height=10, fig.width=8}
mort_proportions_plot <-
  mort_proportions_plot_fam /
  habitat_plot +
  plot_annotation(tag_levels = "A") +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom") 

mort_proportions_plot

ggsave(mort_proportions_plot, file = paste0("fig1.pdf"), path = here::here("figs"), height = 10, width = 12)
```


## Batoid plot


```{r, fig.height=8, fig.width=8, message = TRUE}
mort_proportions_plot_fam_bat <-
  ggplot() +
  geom_point(data = mort_summary %>% 
           filter(!gear_class %in% c("handline", "purse seine", "pole and line") &
                  group != "Sharks") %>% 
              mutate(estimate_type = str_to_sentence(estimate_type),
                     gear_class = str_to_title(gear_class)) %>% 
           drop_na(family) %>% 
             mutate(family = as.factor(family)) %>% 
             arrange(desc(family)),
           aes(x = fct_inorder(family),
                y = mortality_prop,
                color = estimate_type, group = estimate_type),
            position = position_jitterdodge(jitter.width = .1),
         show.legend = F) +
  geom_boxplot(data = boxplot_subset %>% 
                 filter(!gear_class %in% c("handline", "purse seine", "pole and line")  &
                  group != "Sharks") %>% 
              mutate(estimate_type = str_to_sentence(estimate_type),
                     gear_class = str_to_title(gear_class)) %>% 
           drop_na(family) %>% 
             mutate(family = as.factor(family)) %>% 
             arrange(desc(family)),
               aes(x = fct_inorder(family), 
                 y = mortality_prop, 
                 fill = estimate_type),
             show.legend = F,
             alpha = 0.5,
         fatten = 1) +
  geom_hline(data = mort_summary_subset_bat %>% 
               mutate(estimate_type = str_to_sentence(estimate_type),
                     gear_class = str_to_title(gear_class)),
             aes(yintercept = mean, color = estimate_type),
             show.legend = F,
             linetype = "dashed",
             alpha = 0.7,
             linewidth = .9) +
  facet_wrap( ~ 
               factor(gear_class,
                    levels = c("Longline", "Gillnet", "Trawl"))) +
  labs(x = "",
       y = "Fishing mortality",
       color = "Estimate type",
       fill = "Estimate type") +
  scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1)) +
  scale_color_manual(values = c("#414487FF", "#22A884FF")) +
  scale_fill_manual(values = c("#414487FF", "#22A884FF")) +
  coord_flip() +
  theme_bw(base_size = 14) +
  theme(axis.text = element_text( color = "black"),
        axis.title = element_text( color = "black"),
        legend.position = "bottom",
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        strip.background = element_rect(fill = "transparent"),
        panel.spacing.x = unit(5, "mm"))

#ggsave(mort_proportions_plot_fam, file = paste0("mort_proportions_plot_fam.png"), path = here::here("figs"), height = 12, width = 8)
```

```{r, fig.height=8, fig.width=6}
habitat_plot_bat <- 
  ggplot() +
  geom_point(data = mort_summary %>% 
         filter(!gear_class %in% c("handline", "purse seine", "pole and line") &
                  !is.na(habitat_associated) &
                  group != "Sharks") %>% 
         mutate(estimate_type = str_to_sentence(estimate_type),
                gear_class = str_to_title(gear_class)) %>% 
         mutate(habitat_associated = str_to_title(habitat_associated),
                gear_class = str_to_title(gear_class)) %>% 
         mutate(habitat_associated = as.factor(habitat_associated)) %>% 
         arrange(desc(habitat_associated)),
         aes(x = fct_inorder(habitat_associated),
             y = mortality_prop, 
             color = estimate_type, group = estimate_type),
             position = position_jitterdodge(jitter.width = .1)) +
  geom_boxplot(data = habitat_subset %>% 
         filter(!gear_class %in% c("handline", "purse seine", "pole and line") &
                  !is.na(habitat_associated) &
                  group != "Sharks") %>% 
         mutate(estimate_type = str_to_sentence(estimate_type),
                gear_class = str_to_title(gear_class)) %>% 
         mutate(habitat_associated = str_to_title(habitat_associated),
                gear_class = str_to_title(gear_class)) %>% 
         mutate(habitat_associated = as.factor(habitat_associated)) %>% 
         arrange(desc(habitat_associated)),
         aes(x = fct_inorder(habitat_associated), 
             y = mortality_prop, 
             fill = estimate_type),
               alpha = 0.5,
         fatten = 1) +
  geom_hline(data = mort_summary_subset_bat %>% 
               mutate(estimate_type = str_to_sentence(estimate_type),
                     gear_class = str_to_title(gear_class)),
             aes(yintercept = mean, color = estimate_type),
             show.legend = F,
             linetype = "dashed",
             alpha = 0.7,
             linewidth = .9) +
  facet_wrap(~ factor(gear_class,
                    levels = c("Longline", "Gillnet", "Trawl"))) +
  labs(x = "",
       y = "Fishing mortality",
       color = "Estimate type",
       fill = "Estimate type") +
  scale_color_manual(values = c("#414487FF", "#22A884FF")) +
  scale_fill_manual(values = c("#414487FF", "#22A884FF")) +
  coord_flip() +
  theme_bw(base_size = 14) +
  theme(axis.text = element_text(color = "black"),
        axis.title = element_text(color = "black"),
        legend.position = "bottom",
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        strip.background = element_rect(fill = "transparent"),
        panel.spacing.x = unit(5, "mm"))
```

```{r, fig.height=10, fig.width=8}
mort_proportions_plot_bat <-
  mort_proportions_plot_fam_bat /
  habitat_plot_bat +
  plot_annotation(tag_levels = "A") +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom") 

mort_proportions_plot_bat

ggsave(mort_proportions_plot_bat, file = paste0("mort_proportions_plot_bat.pdf"), path = here::here("figs", "supp"), height = 12, width = 15)
```


```{r, fig.height=10, fig.width=7}
# create species count plot
obs_count_plot <-
  prm_elasmo_subset %>% 
  filter(group == "Sharks") %>% 
  group_by(scientific_name) %>% 
  count() %>% 
  ungroup() %>% 
  arrange(desc(n)) %>% 
  mutate(scientific_name = as.factor(scientific_name)) %>% 
  slice_head(n = 20) %>% 
  ggplot() +
  geom_col(aes(x = fct_reorder(scientific_name, n), y = n),
           fill = "blue4",
           alpha=.7,
           width = .8,
           color = "black") +
  coord_flip() +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0, 25)) +
  labs(x = "",
       y = "Number of observations per species") +
  theme_bw() +
  theme(axis.text.y = element_text(color = "black", size = 10, face = "italic"),
        axis.text.x = element_text(color = "black", size = 10),
        axis.title = element_text(color = "black", size = 12),
        panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank())

ggsave(obs_count_plot, file = paste0("obs_count_plot.pdf"), path = here::here("figs", "supp"), height = 10, width = 8)
```




















