---
title: "fish_base"
author: "Leonardo Feitosa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rfishbase)
library(here)
library(janitor)
library(googlesheets4)
library(vroom)

# Set file paths
basedir <- "G:/Meu Drive/PRM review/"
datadir <- file.path(basedir, "data/fish_base_data")
outdir <- file.path(basedir, "data/outputs") # calls present data from raster files
```

```{r}
test_fishbase <- load_taxa() %>% 
  filter(Class == "Elasmobranchii") %>% 
  select(Species, Family) %>% 
  rename(scientific_name = Species,
         family = Family)
```


```{r}
# get shark and ray scientific names
shark_spp <- fb_tbl("species") %>% 
  clean_names() %>% 
  filter(str_detect(genus, "Carcharhinus|Glyphis|Isogomphodon|Lamiopsis|Loxodon|Rhizoprionodon|Scoliodon|Triaenodon|Galeocerdo|Chaenogaleus|Hemigaleus|Hemipristis|Paragaleus|Leptocharias|Ctenacis|Eridacnis|Gollum|Proscyllium|Pseudotriakis|Apristurus|Asymbolus|Bythaelurus|Cephalurus|Figaro|Galeus|Halaelurus|Haploblepharus|Holohalaelurus|Parmaturus|Pentanchus|Atelomycterus|Aulohalaelurus|Cephaloscyllium|Poroderma|Schroederichthys|Scyliorhinus|Sphyrna|Furgaleus|Galeorhinus|Hemitriakis|Hypogaleus|Iago|Mustelus|Triakis|Scylliogaleus|Heterodontus|Hexanchus|Notorynchus|Chlamydoselachus|Carcharias|Carcharias|Carcharodon|Isurus|Lamna|Alopias|Cetorhinus|Megachasma|Mitsukurina|Odontaspis|Brachaelurus|inglymostoma|Nebrius|Chiloscyllium|Hemiscyllium|Orectolobus|Eucrossorhinus|Sutorectus|Cirrhoscyllium|Parascyllium|Rhincodon|Stegostoma|Pristiophorus|Pliotrema|Squatina|Squalus|Etmopterus|Centrophorus|Daenia|Dalatias|Euprotomicroides|Heteroscymnoides|Isistius|Mollisquama|Squaliolus|Echinorhinus|Aculeola|Centroscyllium|Centroscymnus|Scymnodalatias|Scymnodon|Somniosus|Cirrhigaleus|Oxynotus|Aetobatus|Bathytoshia|trygon|Dasyatis|Himantura|Hypanus|Maculabatis|Pastinachus|Pateobatis|Taeniura|Urogymnus|Gymnura|Aetomylaeus|Myliobatis|Manta|Mobula|Plesiobatis|Rhinoptera|Spinilophus|Urolophus|Urobatis|raja|batis|Springeria|Irolita|Sympterygia|Gurgesiella|Dipturus|Hongeo|Okamejei|Raja|Rajella|Glaucostegus|Platyrhin|Pristis|Anoxypristis|Acroteriobatus|Pseudobatos|Rhinobatos|Rhina|Rhynchobatus|Aptychotrema|Trygonorrhina|Zapteryx|Zanobatus|Hypnos|Benthobatis|Diplobatis|Discopyge|Narcine|Crassinarke|Electrolux|Heteronarce|Narke|Temera|Typhlonarke|Tetronarce|Torpedo")) %>%  
  filter(!str_detect(genus, "Potamotrygon|Paratrygon|Heliotrygon|Plesiotrygon|Glyphis"))  %>% # remove freshwater stingrays and sharks
  select(spec_code, genus, species, species_ref_no, fam_code, demers_pelag, longevity_wild, length, l_type_max_m) %>% 
  unite(scientific_name, c("genus", "species"), sep = " ", remove = FALSE)

write_csv(shark_spp, file = file.path(basedir, "data", "shark_spp_list.csv"), col_names = TRUE)

```



```{r}
# call PRM dataset
prm_elasmo <- read_csv(here("data", "prm_dataset.csv"))

prm_elasmo <- prm_elasmo %>% 
  rename(scientific_name = species)

# Call saup species list from Worm et al (XXXX)
saup_spp2 <- read_csv(here("data", "sau_spp_taxonomy_ref_full.csv"))

saup_spp <- read_csv(here("data", "sau_spp_taxonomy_ref.csv"))

# create full dataset of species present in saup
saup_full <- saup_spp2 %>% 
  left_join(saup_spp, by = "scientific_name") %>% 
  mutate(family = str_to_sentence(family_name),
         order = str_to_sentence(order_name)) %>% 
  select(-c(genus_name, family_name, order_name)) %>% 
  relocate(family, .after = common_name) %>% 
  relocate(order, .before = ventilation_method)

#write_csv(saup_full, file = here("data", "sau_spp_taxonomy_ref_full.csv"), col_names = TRUE, na = "")

# call the weight to count conversion data by species
weight_conv <- read_csv(here("data", "spp_weight_count_conversion.csv"))

# call the intrinsic population growth rate from Bradley et al (XXXX)
r_data <- read_csv(here("data", "r_estimate_fish.csv")) %>% 
  rename(scientific_name = SciName) %>% 
  pivot_longer(cols = r_fin,
               names_to = "pop_growth_rate_measure",
               values_to = "value")

# call in the intrinsic growth rate data and wrangle it to convert lambda to r
int_growth <- read_csv(here("data", "intrinsic_pop_growth_rates.csv")) %>% 
  mutate(scientific_name = str_replace(scientific_name, "_", " "))

#write_csv(int_growth, file = here("data", "intrinsic_pop_growth_rates.csv"), col_names = TRUE, na = "")

r_data_merge <- shark_spp %>% 
  left_join(r_data, by = "scientific_name")

r_data_full <- bind_rows(r_data_merge, int_growth) %>% 
  drop_na(pop_growth_rate_measure) %>% 
  select(scientific_name, pop_growth_rate_measure, value, areas, reference, observations) %>% 
  mutate(r_value = case_when(
    pop_growth_rate_measure == "lambda" ~ log(value),
    TRUE ~ value
  )) %>% 
  group_by(scientific_name) %>% 
  mutate(mean_r = mean(r_value)) %>% # calculates mean r values per species because some species have different r values depending on method/sampling area
  relocate(areas, .after = scientific_name) %>% 
  relocate(reference, .after = mean_r) %>% 
  relocate(observations, .after = reference) %>%
  distinct()
   

#write_csv(r_data_full, file = here("data", "intrinsic_pop_growth_rates_full.csv"), col_names = TRUE, na = "")
```

```{r}
# join shark_spp data from fishbase with the saup species list, the species specific weight to count conversion coefficients, and intrinsic population growth rates
shark_saup_join <- saup_spp %>% 
  bind_rows(int_growth) %>% 
  left_join(test_fishbase, by = "scientific_name") %>% 
  left_join(weight_conv, by = "scientific_name") %>% 
  select(-c(habitat, value, r_value, reference, observations, areas, pop_growth_rate_measure)) %>% 
  relocate(family, .after = scientific_name) %>% 
  mutate(family = case_when(
    str_detect(scientific_name, "dae") ~ scientific_name,
    str_detect(scientific_name, "Sphyrna") ~ "Sphyrnidae",
    str_detect(scientific_name, "Alopias") ~ "Alopidae",
    str_detect(scientific_name, "Scyliorhinus") ~ "Scyliorhinidae",
    str_detect(scientific_name, "Squalus") ~ "Squalidae",
    str_detect(scientific_name, "Etmopterus") ~ "Etmopteridae",
    str_detect(scientific_name, "Mustelus") ~ "Triakidae",
    TRUE ~ family
  )) %>% 
  distinct() %>% 
  arrange(scientific_name) %>% 
  drop_na(mean_r)

write_csv(shark_saup_join, file = here("data", "shark_saup_fishbase_spp_list.csv"), col_names = TRUE)
```



```{r}
# Join temp_join with prm_elasmo datasets
prm_join <- prm_elasmo %>% 
  left_join(temp_join, by = "scientific_name") %>% 
  select(-c(median_temp)) %>% 
  rename(median_temp = temp_preferred) %>% 
  relocate(median_temp, .after = reproductive_mode) 

 
sheet_write(prm_join, sheet = "prm_dataset_temp_hab")

write_csv(prm_join, file = file.path(basedir, "data", "prm_dataset_temp_hab.csv"), col_names = TRUE)
```


