---
title: "Untitled"
author: "Leonardo Feitosa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(vegan)
library(ggrepel)
library(MetBrewer)
library(ggpp)
library(patchwork)
library(FactoMineR)
library(factoextra)
# Set data paths
basedir <- "G:/Meu Drive/PRM review/"
datadir <- file.path(basedir, "data/fish_base_data")
outdir <- file.path(basedir, "data/outputs") # calls present data from raster files
```

```{r}
prm_elasmo <- read_csv(here("data", "prm_dataset.csv"))

prm_elasmo <- prm_elasmo %>% 
  rename(scientific_name = species)

# sp counts per estimate type
avm_sp_count <- prm_elasmo %>%
  filter(estimate_type == "at-vessel mortality") %>% 
  distinct(scientific_name) %>% 
  count()

prm_sp_count <- prm_elasmo %>%
  filter(estimate_type == "post-release mortality") %>% 
  distinct(scientific_name) %>% 
  count()

```

```{r}
# create data subset with variables that will be used in the random forest model
prm_elasmo_subset <- prm_elasmo %>% 
  select(scientific_name, gear_class, habitat_associated, estimate_type, estimate, sample_size,
         method, ventilation_method, max_size_cm, measure, median_depth, reproductive_mode, family) %>% 
   mutate(max_size_cm = case_when( # filling missing information based on the average per group
    scientific_name == "Dasyatis sp" ~ 146.22,
    scientific_name == "Squalus sp" ~ 141.12,
    scientific_name == "Mustelus sp" ~ 171.9,
    scientific_name == "Centrophorus sp" ~ 165.75,  
    scientific_name == "sharks" ~ 347.2639,
    scientific_name == "rays" ~ 170.2222, # only calculated for the batoid species with disk width measures
    TRUE ~ max_size_cm
  )) %>% 
  mutate(median_depth = case_when( # filling missing information based on the average per group
    scientific_name == "Dasyatis sp" ~ 139.33,
    scientific_name == "Squalus sp" ~ 601.875,
    scientific_name == "Mustelus sp" ~ 254.3929,
    scientific_name == "Centrophorus sp" ~ 1136.25,
    scientific_name == "sharks" ~ 313.2104,
    scientific_name == "rays" ~ 120.5278,
    TRUE ~ median_depth
  )) %>% 
  mutate(measure = case_when(
    scientific_name == "sharks" ~ "total_length",
    scientific_name %in% c("rays", "Dasyatis sp") ~ "disk_width",
    TRUE ~ measure
  )) %>% 
  mutate(reproductive_mode = case_when(
    scientific_name == "sharks" ~ "yolk-sac viviparity",
    scientific_name == "rays" ~ "yolk-sac viviparity",
    TRUE ~ reproductive_mode
  )) %>%
  mutate_if(is.character, as.factor)

# Create subset of the whole dataset with at-vessel mortality and calculate the weighted averages per species and gear
elasmo_avm <- prm_elasmo_subset %>%
  filter(estimate_type == "at-vessel mortality" & estimate > 0) %>% 
  mutate(est_count = sample_size * estimate) %>% 
  group_by(scientific_name, gear_class) %>% 
  mutate(mortality_prop = sum(est_count) / sum(sample_size)) %>% 
  drop_na() %>% 
  filter(!gear_class %in% c("handline", "purse seine"))

# Create subset of the whole dataset with post-release mortality and calculate the weighted averages per species and gear
elasmo_prm <- prm_elasmo_subset %>% 
  filter(estimate_type == "post-release mortality" & estimate > 0) %>% 
  mutate(est_count = sample_size * estimate) %>% 
  group_by(scientific_name, gear_class) %>% 
  mutate(mortality_prop = sum(est_count) / sum(sample_size)) %>% 
  drop_na() %>% 
  filter(!gear_class %in% c("handline", "purse seine", "pole and line"))
```

## AVM NMDS 
```{r}
# calculate an nMDS for AVM
## create subset of categorical data
avm_cat <- elasmo_avm %>% 
  select(scientific_name, gear_class, habitat_associated, ventilation_method, reproductive_mode, family)


## create subset of numerical data
avm_num <- elasmo_avm %>% 
  ungroup() %>% 
  select(mortality_prop, est_count, median_depth, max_size_cm) 


#avm_dist <- vegdist(avm_num, method = "euclid")
avm_dist_mat <- as.matrix(avm_num, labels = T)

set.seed(123)

avm_mds <- metaMDS(avm_dist_mat, k = 2, trymax = 400, distance = "bray", trace = T, autotransform = FALSE)

stressplot(avm_mds)

plot(avm_mds, display = "sites")

# Assembling NMDS results
data_scores_sp_avm <- as.data.frame(scores(avm_mds, "sites"))
data_scores_sp_avm$scientific_name <- as.factor(avm_cat$scientific_name)
data_scores_sp_avm$gear_class <- as.factor(avm_cat$gear_class)
data_scores_sp_avm$habitat_associated <- as.factor(avm_cat$habitat_associated)
data_scores_sp_avm$ventilation_method <- as.factor(avm_cat$ventilation_method)
data_scores_sp_avm$reproductive_mode <- as.factor(avm_cat$reproductive_mode)
data_scores_sp_avm$family <- as.factor(avm_cat$family)

species.scores_avm <- as.data.frame(scores(avm_mds,"species"))
species.scores_avm$cont <- (rownames(species.scores_avm)) 

fit_avm <- envfit(avm_mds, avm_num, perm = 1000)
vars_avm <- c("mort_prop", "est_count", "median_depth", "max_size")
fit_df_avm <- as.data.frame(scores(fit_avm, display = "vectors"))
fit_df_avm$vars_avm <- (rownames(vars_avm))

```


## Plot NMDS 
```{r, fig.width=10, fig.height=8}
avm_nmds_plot <- 
  ggplot() +   
  geom_point(data = data_scores_sp_avm,
             aes(x = NMDS1, y = NMDS2,
                 color = gear_class),
             size = 2,
             show.legend = T,
             alpha = .7) +
  stat_ellipse(data = data_scores_sp_avm,
               aes(x = NMDS1, y = NMDS2,
                 color = gear_class),
               linewidth = .8,
               alpha = .7) +
  geom_segment(data = fit_df_avm, 
               aes(x = -0, xend = NMDS1,
                   y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")),
               linewidth = .8,
               alpha = 0.3) +
  geom_label_repel(data = fit_df_avm,
                   aes(x = NMDS1,
                       y = NMDS2,
                       label = vars),
                   position = position_nudge_center(x = .2, y = .01,
                                                    center_x = 0, center_y = 0),
                   fontface = "bold",
                   alpha = 0.5) +
  labs(fill = "",
       shape = "",
       color = "",
       title = "AVM") +
  coord_equal() + 
  theme_bw() +
  theme(legend.key.size = unit(0.6, "cm"),
        legend.background = element_rect(fill = "transparent"),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15),
        legend.position = "bottom",
        axis.title = element_text(size = 13, face = "bold", color = "black"),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank()) +
  guides(shape = "none")

```


## PRM NMDS 
```{r}
# calculate an nMDS for AVM
## create subset of categorical data
prm_cat <- elasmo_prm %>% 
  select(scientific_name, gear_class, habitat_associated, ventilation_method, reproductive_mode, family)


## create subset of numerical data
prm_num <- elasmo_prm %>% 
  ungroup() %>% 
  select(mortality_prop, est_count, median_depth, max_size_cm) 


#avm_dist <- vegdist(avm_num, method = "euclid")
prm_dist_mat <- as.matrix(prm_num, labels = T)

set.seed(123)

prm_mds <- metaMDS(prm_dist_mat, k = 2, trymax = 400, distance = "bray", trace = T, autotransform = FALSE)

stressplot(prm_mds)


# Assembling NMDS results
data_scores_sp_prm <- as.data.frame(scores(prm_mds, "sites"))
data_scores_sp_prm$scientific_name <- as.factor(prm_cat$scientific_name)
data_scores_sp_prm$gear_class <- as.factor(prm_cat$gear_class)
data_scores_sp_prm$habitat_associated <- as.factor(prm_cat$habitat_associated)
data_scores_sp_prm$ventilation_method <- as.factor(prm_cat$ventilation_method)
data_scores_sp_prm$reproductive_mode <- as.factor(prm_cat$reproductive_mode)
data_scores_sp_prm$family <- as.factor(prm_cat$family)

species.scores_prm <- as.data.frame(scores(prm_mds,"species"))
species.scores_prm$cont <- (rownames(species.scores_prm)) 

fit_prm <- envfit(prm_mds, prm_num, perm = 1000)
vars_prm <- c("mort_prop", "est_count", "median_depth", "max_size")
fit_df_prm <- as.data.frame(scores(fit_prm, display = "vectors"))
fit_df_prm$vars_prm <- (rownames(vars_prm))

```


## Plot PRM NMDS 
```{r, fig.width=10, fig.height=8}
prm_nmds_plot <-
  ggplot() +   
  geom_point(data = data_scores_sp_prm,
             aes(x = NMDS1, y = NMDS2,
                 color = gear_class),
             size = 2,
             show.legend = T,
             alpha = .7) +
  stat_ellipse(data = data_scores_sp_prm,
               aes(x = NMDS1, y = NMDS2,
                 color = gear_class),
               linewidth = .8,
               alpha = .7) +
  geom_segment(data = fit_df_prm, 
               aes(x = -0, xend = NMDS1,
                   y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")),
               linewidth = .8,
               alpha = 0.3) +
  geom_label_repel(data = fit_df_prm,
                   aes(x = NMDS1,
                       y = NMDS2,
                       label = vars),
                   position = position_nudge_center(x = .2, y = .01,
                                                    center_x = 0, center_y = 0),
                   fontface = "bold",
                   alpha = 0.5) +
  labs(fill = "",
       shape = "",
       color = "",
       title = "PRM") +
  coord_equal() + 
  theme_bw() +
  theme(legend.key.size = unit(0.6, "cm"),
        legend.background = element_rect(fill = "transparent"),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15),
        legend.position = "bottom",
        axis.title = element_text(size = 13, face = "bold", color = "black"),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank()) +
  guides(shape = "none")

```


```{r, fig.height=10, fig.width=10}
avm_nmds_plot / 
  prm_nmds_plot +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom")
```


## FAMD analysis
gear_class + ventilation_method + median_depth + max_size_cm + habitat_associated + reproductive_mode
```{r}
# data prep for FAMD
elasmo_avm_famd <- elasmo_avm %>% 
  select(mortality_prop, gear_class, ventilation_method, median_depth, max_size_cm, habitat_associated, reproductive_mode, family)

avm_famd <- FAMD(elasmo_avm_famd, graph = FALSE)

avm_var <- get_famd_var(avm_famd)
avm_var
```

```{r}
# Plot of variables
fviz_famd_var(avm_famd, repel = TRUE)
# Contribution to the first dimension
fviz_contrib(avm_famd, "var", axes = 1)
# Contribution to the second dimension
fviz_contrib(avm_famd, "var", axes = 2)
```



```{r}
fviz_mfa_ind(avm_famd, 
             habillage = "gear_class", # color by groups 
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, ellipse.type = "confidence", 
             repel = FALSE # Avoid text overlapping
             ) 
```

```{r}
# data prep for FAMD
elasmo_prm_famd <- elasmo_prm %>% 
  select(mortality_prop, gear_class, ventilation_method, median_depth, max_size_cm, habitat_associated, reproductive_mode, family)

prm_famd <- FAMD(elasmo_prm_famd, graph = FALSE)

prm_var <- get_famd_var(prm_famd)
prm_var 
```

```{r}
fviz_mfa_ind(prm_famd, 
             habillage = "gear_class", # color by groups 
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE, ellipse.type = "confidence", 
             repel = FALSE # Avoid text overlapping
             ) 
```


```{r}
avm_famd <- MFA(elasmo_avm_famd, graph = FALSE, group = gear_class)


fviz_mfa_quali_biplot()
```














